import { Link } from 'wouter';
import { ArrowUpRight, CalendarDays, ChevronRight, PenLine, Plus, WalletCards } from 'lucide-react';
import { useGetDashboardSummary, useListLetters, useListReminders } from '@workspace/api-client-react';
import { AppShell, AuthGate, Button, EmptyState, PageIntro, Skeleton } from '@/components/app-shell';

const money = (n = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
const date = (v: string) => new Date(v).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

export default function Dashboard() {
  const summary = useGetDashboardSummary();
  const letters = useListLetters();
  const reminders = useListReminders();
  const today = new Date().toISOString().slice(0, 10);
  const upcoming = (reminders.data ?? []).filter(r => r.endDate >= today).slice(0, 3);
  return <AuthGate><AppShell><PageIntro eyebrow="good morning, y" title={<>Keep close<br /><em>to what matters.</em></>} detail="A soft landing for the practical things — and the little things that are anything but practical." action={<Link href="/feed" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-[13px] font-semibold text-primary-foreground hover:opacity-90" data-testid="link-write-letter"><PenLine size={16} /> Write a letter</Link>} />
    <div className="grid gap-4 sm:grid-cols-3 fade-up-2">
      {[{ label: 'in your wallets', value: summary.data ? money(summary.data.totalMoney) : '—', note: `${summary.data?.walletCount ?? 0} little pockets`, href: '/wallet', icon: WalletCards }, { label: 'on the horizon', value: upcoming.length ? `${upcoming.length}` : '—', note: upcoming.length === 1 ? 'one reminder soon' : 'things coming up', href: '/scheduler', icon: CalendarDays }, { label: 'letters kept', value: letters.data ? `${letters.data.length}` : '—', note: 'words worth keeping', href: '/feed', icon: PenLine }].map(({ label, value, note, href, icon: Icon }) => <Link href={href} key={label} className="group rounded-[22px] border border-border bg-card p-5 transition-transform hover:-translate-y-0.5" data-testid={`card-summary-${label.replaceAll(' ', '-')}`}><div className="mb-8 flex items-center justify-between"><span className="text-[11px] uppercase tracking-[.12em] text-muted-foreground">{label}</span><Icon size={17} className="text-[hsl(var(--accent-foreground))]" /></div><div className="font-display text-[36px] leading-none">{value}</div><div className="mt-2 flex items-center justify-between text-[12px] text-muted-foreground"><span>{note}</span><ArrowUpRight size={15} className="opacity-0 transition-opacity group-hover:opacity-100" /></div></Link>)}
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr] fade-up-3">
      <section className="rounded-[24px] border border-border bg-card p-6 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">from the feed</div><h2 className="mt-2 font-display text-[29px]">Recent letters</h2></div><Link href="/feed" className="text-[12px] font-semibold text-[hsl(var(--accent-foreground))]" data-testid="link-see-all-letters">See all <ChevronRight className="inline" size={14} /></Link></div>{letters.isLoading ? <div className="space-y-4"><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : letters.isError ? <div className="rounded-xl bg-destructive/10 p-4 text-[13px] text-destructive" data-testid="status-dashboard-letters-error">Couldn’t bring the letters in right now.</div> : letters.data?.length ? <div className="space-y-1">{letters.data.slice(0, 3).map((letter, i) => <Link href="/feed" key={letter.id} className="flex items-center gap-4 rounded-xl px-2 py-3 transition-colors hover:bg-muted/70" data-testid={`row-recent-letter-${letter.id}`}><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-[13px] font-semibold ${i % 2 ? 'bg-secondary text-secondary-foreground' : 'bg-accent/35 text-accent-foreground'}`}>0{i + 1}</div><div className="min-w-0 flex-1"><h3 className="truncate text-[14px] font-semibold">{letter.title}</h3><p className="mt-1 truncate text-[12px] text-muted-foreground">{letter.content.replace(/<[^>]*>/g, '').slice(0, 90)}</p></div><span className="font-mono text-[10px] text-muted-foreground">{date(letter.createdAt)}</span></Link>)}</div> : <EmptyState title="Nothing written yet" detail="A blank page can be a lovely beginning." action={<Link href="/feed" className="text-[12px] font-semibold text-[hsl(var(--accent-foreground))]" data-testid="link-empty-letter">Open the feed</Link>} />}</section>
      <section className="rounded-[24px] bg-secondary p-6 text-secondary-foreground sm:p-7"><div className="mb-7 flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-secondary-foreground/55">next up</div><h2 className="mt-2 font-display text-[29px]">The week ahead</h2></div><Link href="/scheduler" className="grid h-9 w-9 place-items-center rounded-full bg-secondary-foreground/10 hover:bg-secondary-foreground/15" data-testid="link-open-scheduler"><ArrowUpRight size={16} /></Link></div>{reminders.isLoading ? <div className="space-y-3"><Skeleton className="h-14 bg-secondary-foreground/10" /><Skeleton className="h-14 bg-secondary-foreground/10" /></div> : upcoming.length ? <div className="space-y-3">{upcoming.map(item => <div key={item.id} className="flex gap-3 rounded-xl border border-secondary-foreground/10 bg-secondary-foreground/5 p-3" data-testid={`row-upcoming-reminder-${item.id}`}><div className="mt-1 h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: item.color }} /><div className="min-w-0"><p className="truncate text-[13px] font-semibold">{item.title}</p><p className="mt-1 text-[11px] text-secondary-foreground/60">{date(item.startDate)}{item.startTime ? ` · ${item.startTime}` : ''}</p></div></div>)}</div> : <p className="rounded-xl border border-secondary-foreground/10 bg-secondary-foreground/5 p-4 text-[13px] text-secondary-foreground/65" data-testid="empty-upcoming-reminders">A clear week ahead. Nice.</p>}<Link href="/scheduler" className="mt-7 inline-flex items-center gap-2 text-[12px] font-semibold" data-testid="link-plan-week"><Plus size={14} /> Add something</Link></section>
    </div>
    <section className="mt-5 rounded-[24px] border border-border bg-card p-6 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">money, gently</div><h2 className="mt-2 font-display text-[29px]">Recent movement</h2></div><Link href="/wallet" className="text-[12px] font-semibold text-[hsl(var(--accent-foreground))]" data-testid="link-see-wallet">Open wallet <ChevronRight className="inline" size={14} /></Link></div>{summary.isLoading ? <Skeleton className="h-14" /> : summary.data?.recentTransactions?.length ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{summary.data.recentTransactions.slice(0, 4).map(tx => <div key={tx.id} className="flex items-center justify-between rounded-xl bg-muted/50 px-4 py-3" data-testid={`row-dashboard-transaction-${tx.id}`}><div><p className="text-[13px] font-semibold">{tx.merchantOrSource}</p><p className="mt-1 text-[11px] text-muted-foreground">{date(tx.transactionDate)}</p></div><span className={`font-mono text-[12px] font-medium ${tx.type === 'deposit' ? 'text-[hsl(var(--chart-5))]' : 'text-foreground'}`}>{tx.type === 'deposit' ? '+' : '−'}{money(tx.amount)}</span></div>)}</div> : <p className="text-[13px] text-muted-foreground" data-testid="empty-dashboard-transactions">No money movement yet.</p>}</section>
  </AppShell></AuthGate>;
}