import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Pencil, Plus, Trash2, WalletCards } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetDashboardSummaryQueryKey, getListTransactionsQueryKey, getListWalletsQueryKey, useCreateTransaction, useCreateWallet, useDeleteTransaction, useDeleteWallet, useGetDashboardSummary, useListTransactions, useListWallets, useUpdateTransaction, useUpdateWallet } from '@workspace/api-client-react';
import type { Transaction, TransactionInputType, Wallet } from '@workspace/api-client-react';
import { AppShell, AuthGate, Button, EmptyState, Field, Modal, PageIntro, Skeleton, inputClass } from '@/components/app-shell';

const money = (n = 0) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(n);
const date = (v: string) => new Date(v).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
const localDateTime = (v?: string) => v ? new Date(v).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16);

function WalletForm({ wallet, onClose }: { wallet?: Wallet; onClose: () => void }) {
  const queryClient = useQueryClient();
  const create = useCreateWallet(), update = useUpdateWallet();
  const [name, setName] = useState(wallet?.name ?? '');
  const [targetAmount, setTargetAmount] = useState(wallet?.targetAmount?.toString() ?? '');
  const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); const data = { name, targetAmount: targetAmount === '' ? null : Number(targetAmount) }; const done = () => { queryClient.invalidateQueries({ queryKey: getListWalletsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); onClose(); }; wallet ? update.mutate({ id: wallet.id, data }, { onSuccess: done, onError: () => setError('Couldn’t update this wallet.') }) : create.mutate({ data }, { onSuccess: done, onError: () => setError('Couldn’t create this wallet.') }); };
  return <Modal title={wallet ? 'Rename wallet' : 'A new little pocket'} kicker="wallet collection" onClose={onClose}><form onSubmit={submit} className="space-y-5"><Field label="Name"><input required maxLength={100} value={name} onChange={e => setName(e.target.value)} className={inputClass} placeholder="Something you’re saving for" data-testid="input-wallet-name" /></Field><Field label="Target amount" hint="Optional — a soft destination, not a demand."><input type="number" min="0" step="0.01" value={targetAmount} onChange={e => setTargetAmount(e.target.value)} className={inputClass} placeholder="0.00" data-testid="input-wallet-target" /></Field>{error && <p className="rounded-xl bg-destructive/10 p-3 text-[12px] text-destructive" data-testid="status-wallet-error">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose} testId="button-cancel-wallet">Not now</Button><Button type="submit" disabled={create.isPending || update.isPending || !name.trim()} testId="button-save-wallet">{create.isPending || update.isPending ? 'Saving...' : 'Save wallet'}</Button></div></form></Modal>;
}

function TransactionForm({ transaction, wallets, onClose }: { transaction?: Transaction; wallets: Wallet[]; onClose: () => void }) {
  const queryClient = useQueryClient();
  const create = useCreateTransaction(), update = useUpdateTransaction();
  const [walletId, setWalletId] = useState(transaction?.walletId?.toString() ?? '');
  const [type, setType] = useState<TransactionInputType>(transaction?.type ?? 'deposit');
  const [amount, setAmount] = useState(transaction?.amount.toString() ?? '');
  const [merchantOrSource, setMerchantOrSource] = useState(transaction?.merchantOrSource ?? '');
  const [description, setDescription] = useState(transaction?.description ?? '');
  const [transactionDate, setTransactionDate] = useState(localDateTime(transaction?.transactionDate));
  const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); const data = { walletId: walletId ? Number(walletId) : null, type, amount: Number(amount), merchantOrSource, description, transactionDate: new Date(transactionDate).toISOString() }; const done = () => { queryClient.invalidateQueries({ queryKey: getListTransactionsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); queryClient.invalidateQueries({ queryKey: getListWalletsQueryKey() }); onClose(); }; transaction ? update.mutate({ id: transaction.id, data }, { onSuccess: done, onError: () => setError('Couldn’t update this transaction.') }) : create.mutate({ data }, { onSuccess: done, onError: () => setError('Couldn’t save this transaction.') }); };
  return <Modal title={transaction ? 'Edit movement' : 'Add a movement'} kicker="wallet history" onClose={onClose}><form onSubmit={submit} className="space-y-5"><div className="grid grid-cols-2 gap-2 rounded-xl bg-muted p-1"><button type="button" onClick={() => setType('deposit')} className={`min-h-10 rounded-lg text-[12px] font-semibold ${type === 'deposit' ? 'bg-card shadow-sm' : 'text-muted-foreground'}`} data-testid="button-transaction-deposit">Money in</button><button type="button" onClick={() => setType('withdrawal')} className={`min-h-10 rounded-lg text-[12px] font-semibold ${type === 'withdrawal' ? 'bg-card shadow-sm' : 'text-muted-foreground'}`} data-testid="button-transaction-withdrawal">Money out</button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount"><input required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className={inputClass} placeholder="0.00" data-testid="input-transaction-amount" /></Field><Field label="Date & time"><input required type="datetime-local" value={transactionDate} onChange={e => setTransactionDate(e.target.value)} className={inputClass} data-testid="input-transaction-date" /></Field></div><Field label="From / to"><input required maxLength={180} value={merchantOrSource} onChange={e => setMerchantOrSource(e.target.value)} className={inputClass} placeholder="Where it came from or went" data-testid="input-transaction-source" /></Field>{wallets.length > 0 && <Field label="Wallet"><select value={walletId} onChange={e => setWalletId(e.target.value)} className={inputClass} data-testid="select-transaction-wallet"><option value="">No specific wallet</option>{wallets.map(w => <option value={w.id} key={w.id}>{w.name}</option>)}</select></Field>}<Field label="Note"><textarea maxLength={2000} value={description} onChange={e => setDescription(e.target.value)} className={`${inputClass} min-h-[72px] resize-y py-3`} placeholder="Optional note" data-testid="input-transaction-description" /></Field>{error && <p className="rounded-xl bg-destructive/10 p-3 text-[12px] text-destructive" data-testid="status-transaction-error">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose} testId="button-cancel-transaction">Not now</Button><Button type="submit" disabled={create.isPending || update.isPending || !amount || !merchantOrSource.trim()} testId="button-save-transaction">{create.isPending || update.isPending ? 'Saving...' : 'Save movement'}</Button></div></form></Modal>;
}

function SpendingChart() {
  const [range, setRange] = useState<'daily' | 'weekly' | 'monthly'>('weekly');
  const summary = useGetDashboardSummary({ range });
  const points = summary.data?.spendingPoints ?? [];
  const max = Math.max(...points.map((point) => point.amount), 1);
  const chartPoints = points.map((point, index) => `${(index / Math.max(points.length - 1, 1)) * 100},${100 - (point.amount / max) * 78 - 10}`).join(' ');
  return <section className="mt-5 rounded-[24px] border border-border bg-card p-6 sm:p-7" data-testid="section-spending-chart">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">spending history</div><h2 className="mt-2 font-display text-[30px]">Money out, over time</h2><p className="mt-2 text-[12px] text-muted-foreground">₱{(summary.data?.spendingTotal ?? 0).toLocaleString('en-PH')} in this view</p></div>
      <div className="flex rounded-xl border border-border bg-muted p-1">{(['daily', 'weekly', 'monthly'] as const).map((item) => <button key={item} onClick={() => setRange(item)} className={`rounded-lg px-3 py-2 text-[11px] font-semibold capitalize ${range === item ? 'bg-card shadow-sm' : 'text-muted-foreground'}`} data-testid={`button-spending-${item}`}>{item}</button>)}</div>
    </div>
    {summary.isLoading ? <Skeleton className="mt-6 h-[190px]" /> : <div className="mt-6">
      <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-[190px] w-full overflow-visible" role="img" aria-label={`${range} spending graph`}>
        <defs><linearGradient id="spending-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="hsl(var(--accent))" stopOpacity=".3" /><stop offset="100%" stopColor="hsl(var(--accent))" stopOpacity="0" /></linearGradient></defs>
        <line x1="0" x2="100" y1="90" y2="90" stroke="hsl(var(--border))" strokeWidth=".5" /><line x1="0" x2="100" y1="50" y2="50" stroke="hsl(var(--border))" strokeWidth=".5" strokeDasharray="1 2" />
        {points.length > 1 && <><polyline points={`0,100 ${chartPoints} 100,100`} fill="url(#spending-fill)" stroke="none" /><polyline points={chartPoints} fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></>}
      </svg>
      <div className="mt-2 flex justify-between gap-2">{points.map((point) => <span key={point.label} className="min-w-0 flex-1 truncate text-center font-mono text-[10px] text-muted-foreground">{point.label}</span>)}</div>
    </div>}
  </section>;
}

export default function Wallet() {
  const summary = useGetDashboardSummary({ range: 'monthly' });
  const wallets = useListWallets();
  const transactions = useListTransactions();
  const removeWallet = useDeleteWallet(), removeTransaction = useDeleteTransaction();
  const queryClient = useQueryClient();
  const [modal, setModal] = useState<'wallet' | 'transaction' | null>(null);
  const [selectedWallet, setSelectedWallet] = useState<Wallet>();
  const [selectedTransaction, setSelectedTransaction] = useState<Transaction>();
  const [notice, setNotice] = useState('');
  const list = wallets.data ?? [];
  const txs = transactions.data ?? [];
  const remove = (kind: 'wallet' | 'transaction', id: number, label: string) => { if (window.confirm(`Delete ${label}?`)) { const fn = kind === 'wallet' ? removeWallet : removeTransaction; fn.mutate({ id }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: kind === 'wallet' ? getListWalletsQueryKey() : getListTransactionsQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); setNotice(kind === 'wallet' ? 'Wallet removed.' : 'Movement removed.'); } }); } };
  return <AuthGate><AppShell><PageIntro eyebrow="the wallet / money, made human" title={<>Keep an eye<br /><em>on enough.</em></>} detail="A clear view of what is here, what is moving, and what you are making room for." action={<div className="flex gap-2"><Button variant="outline" onClick={() => { setSelectedWallet(undefined); setModal('wallet'); }} testId="button-new-wallet"><WalletCards size={16} /> New wallet</Button><Button onClick={() => { setSelectedTransaction(undefined); setModal('transaction'); }} testId="button-new-transaction"><Plus size={16} /> Add movement</Button></div>} />
    {notice && <div className="mb-5 rounded-xl bg-[hsl(var(--chart-5)/.14)] px-4 py-3 text-[12px] text-[hsl(var(--chart-5))]" data-testid="status-wallet-success">{notice}</div>}
    <SpendingChart />
    <div className="grid gap-4 sm:grid-cols-3 fade-up-2"><div className="rounded-[22px] bg-primary p-6 text-primary-foreground sm:p-7"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-primary-foreground/55">total, together</div><div className="mt-7 font-display text-[43px] leading-none">{summary.isLoading ? '—' : money(summary.data?.totalMoney)}</div><div className="mt-3 text-[12px] text-primary-foreground/55">across {summary.data?.walletCount ?? list.length} wallets</div></div><div className="rounded-[22px] border border-border bg-card p-6 sm:p-7"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">spent this month</div><div className="mt-7 font-display text-[43px] leading-none">{summary.isLoading ? '—' : money(summary.data?.spendingTotal)}</div><div className="mt-3 text-[12px] text-muted-foreground">a record, not a judgement</div></div><div className="rounded-[22px] bg-secondary p-6 text-secondary-foreground sm:p-7"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-secondary-foreground/55">pockets</div><div className="mt-7 font-display text-[43px] leading-none">{list.length}</div><div className="mt-3 text-[12px] text-secondary-foreground/60">each with its own little purpose</div></div></div>
    <section className="mt-5"><div className="mb-5 flex items-end justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">your collection</div><h2 className="mt-2 font-display text-[30px]">Wallets</h2></div></div>{wallets.isLoading ? <div className="grid gap-4 md:grid-cols-2"><Skeleton className="h-44" /><Skeleton className="h-44" /></div> : list.length ? <div className="grid gap-4 md:grid-cols-2">{list.map((wallet, i) => <div key={wallet.id} className="group rounded-[22px] border border-border bg-card p-6" data-testid={`card-wallet-${wallet.id}`}><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-full ${i % 2 ? 'bg-secondary text-secondary-foreground' : 'bg-accent/30 text-accent-foreground'}`}><WalletCards size={18} /></div><div className="flex gap-1 opacity-0 transition-opacity group-hover:opacity-100"><button onClick={() => { setSelectedWallet(wallet); setModal('wallet'); }} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-muted" aria-label={`Edit ${wallet.name}`} data-testid={`button-edit-wallet-${wallet.id}`}><Pencil size={14} /></button><button onClick={() => remove('wallet', wallet.id, wallet.name)} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={`Delete ${wallet.name}`} data-testid={`button-delete-wallet-${wallet.id}`}><Trash2 size={14} /></button></div></div><div className="mt-7 flex items-end justify-between gap-4"><div><h3 className="font-display text-[27px]">{wallet.name}</h3><p className="mt-1 font-mono text-[12px] text-muted-foreground">{money(wallet.balance)} held</p></div>{wallet.targetAmount != null && <span className="font-mono text-[11px] text-muted-foreground">{Math.round(wallet.progress ?? 0)}%</span>}</div>{wallet.targetAmount != null && <div className="mt-5"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-accent" style={{ width: `${Math.min(100, Math.max(0, wallet.progress ?? 0))}%` }} /></div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>toward {money(wallet.targetAmount)}</span><span>{money(Math.max(0, wallet.targetAmount - wallet.balance))} to go</span></div></div>}</div>)}</div> : <EmptyState title="No wallets yet" detail="Create a pocket for a plan, a dream, or just the shape of a month." action={<Button onClick={() => setModal('wallet')} testId="button-empty-new-wallet"><Plus size={16} /> Create wallet</Button>} />}</section>
    <section className="mt-10 rounded-[24px] border border-border bg-card p-6 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">the paper trail</div><h2 className="mt-2 font-display text-[30px]">Recent movement</h2></div><span className="font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground">{txs.length} entries</span></div>{transactions.isLoading ? <Skeleton className="h-16" /> : txs.length ? <div className="divide-y divide-border">{txs.map(tx => <div key={tx.id} className="flex items-center gap-3 py-4 first:pt-0 last:pb-0" data-testid={`row-transaction-${tx.id}`}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${tx.type === 'deposit' ? 'bg-[hsl(var(--chart-5)/.15)] text-[hsl(var(--chart-5))]' : 'bg-muted text-muted-foreground'}`}>{tx.type === 'deposit' ? <ArrowDownLeft size={16} /> : <ArrowUpRight size={16} />}</div><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold">{tx.merchantOrSource}</p><p className="mt-1 truncate text-[11px] text-muted-foreground">{date(tx.transactionDate)}{tx.description ? ` · ${tx.description}` : ''}</p></div><span className={`font-mono text-[12px] font-medium ${tx.type === 'deposit' ? 'text-[hsl(var(--chart-5))]' : ''}`}>{tx.type === 'deposit' ? '+' : '−'}{money(tx.amount)}</span><div className="flex gap-1 opacity-0 transition-opacity hover:opacity-100 sm:group-hover:opacity-100"><button onClick={() => { setSelectedTransaction(tx); setModal('transaction'); }} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-muted" aria-label={`Edit ${tx.merchantOrSource}`} data-testid={`button-edit-transaction-${tx.id}`}><Pencil size={14} /></button><button onClick={() => remove('transaction', tx.id, 'this movement')} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={`Delete ${tx.merchantOrSource}`} data-testid={`button-delete-transaction-${tx.id}`}><Trash2 size={14} /></button></div></div>)}</div> : <EmptyState title="No movement yet" detail="When money changes shape, keep a note of it here." action={<Button onClick={() => setModal('transaction')} testId="button-empty-new-transaction"><Plus size={16} /> Add movement</Button>} />} </section>
    {modal === 'wallet' && <WalletForm wallet={selectedWallet} onClose={() => setModal(null)} />}{modal === 'transaction' && <TransactionForm transaction={selectedTransaction} wallets={list} onClose={() => setModal(null)} />}
  </AppShell></AuthGate>;
}